version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:3000" # Map port 80 to Next.js default port 3000
    volumes:
      - ./frontend:/usr/src/app # Mount the frontend code for development
    env_file:
      - .env # Load environment variables from the root .env file
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:3000" # Map port 8080 to NestJS default port 3000
    volumes:
      - ./backend:/usr/src/app # Mount the backend code for development
    env_file:
      - .env # Load environment variables from the root .env file
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0 # MongoDB version
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: # Volume for MongoDB data
